-- Malik Roc
-- Paw Bytes
-- drop.sql
-- Creates all PawBytes schema objects

DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Customer_Address CASCADE;

DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Product_Price CASCADE;

DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Employee_Address CASCADE;

DROP TABLE IF EXISTS PawPal_t CASCADE;
DROP TABLE IF EXISTS PawPal_DateGroomed CASCADE;

DROP TABLE IF EXISTS Orders_t CASCADE;
DROP TABLE IF EXISTS Order_Invoice_t CASCADE;

DROP TABLE IF EXISTS Training_Session CASCADE;
DROP TABLE IF EXISTS Attend_Session CASCADE;
DROP TABLE IF EXISTS Conduct_Session CASCADE;


DROP TABLE IF EXISTS Tweet_Treat_Owner CASCADE;
DROP TABLE IF EXISTS Tweet_Treat CASCADE;

--- VIEWS

DROP VIEW  IF EXISTS PawPal_LatestDateGroomed CASCADE;
DROP VIEW  IF EXISTS PawPal_TotalHoursTrained CASCADE;
DROP VIEW  IF EXISTS PawPal CASCADE;
DROP VIEW  IF EXISTS Order_Invoice_UnitPricing CASCADE;
DROP VIEW  IF EXISTS Order_Invoice CASCADE;
DROP VIEW  IF EXISTS Orders CASCADE;
DROP VIEW  IF EXISTS Tweet_Treat_Total CASCADE;
